apiVersion: v2
appVersion: v9.7
description: A Helm chart for XL Deploy
name: xl-deploy
version: 9.7

dependencies:
- name: haproxy-ingress
  version: 0.0.27
  repository: "https://kubernetes-charts-incubator.storage.googleapis.com/"
  condition: haproxy-ingress.install

- name: activemq-artemis
  version: 0.0.2
  repository: "file://./subcharts/activemq-artemis"
  condition: activemq-artemis.install
