# Default values for xl-deploy.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

## Platform on which to install the chart (PlainK8s/AWSEKS)
K8sSetup:
  Platform: PlainK8s

XldMasterCount: 3
XldWorkerCount: 3

## XL-Deploy image version
## Ref: https://hub.docker.com/r/xebialabs/xl-deploy/tags
ImageRepository: "xebialabs/xl-deploy"
ImageTag: "9.7"

## Specify a imagePullPolicy
## Defaults to 'Always' if image tag is 'latest',set to 'IfNotPresent'
ImagePullPolicy: "Always"

## Secrets must be manually created in the namespace.
# ImagePullSecret: xlDeploy

## Install haproxy subchart. If you have haproxy already installed, set 'install' to 'false'.
## If you have any other ingress controller installed, you can set the 'install' to 'false'.
haproxy-ingress:
  install: true
  controller:
    service:
      type: NodePort

## Ingress Configuration
## Ref: https://kubernetes.io/docs/concepts/services-networking/ingress/
ingress:
  Enabled: true
  annotations:
    # ingress.kubernetes.io/tls-acme: "true"
    ingress.kubernetes.io/ssl-redirect: "false"
    kubernetes.io/ingress.class: haproxy
    ingress.kubernetes.io/rewrite-target: /
    ingress.kubernetes.io/affinity: cookie
    ingress.kubernetes.io/session-cookie-name: SESSION_XLD
    ingress.kubernetes.io/session-cookie-strategy: prefix
    ingress.kubernetes.io/config-backend: |
      option httpchk GET /deployit/ha/health HTTP/1.0
  path: /xl-deploy/
  tls: false

#  tls:
#    - secretName: example-secretsName
#      hosts:
#        - example.com

AdminPassword:
  # Provide the admin password to be used

xldLicense:
# Convert xl-deploy.lic files content to base64 ( cat xl-deploy.lic | base64 ) and put the output here

RepositoryKeystore: 
# Convert keystore.jks files content to base64 ( cat keystore.jks | base64 ) and put the output here

KeystorePassphrase:
# Passphrase for keystore.jks file

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 3
  #  memory: 3Gi
  # requests:
  #  cpu: 0.7
  #  memory: 1700Mi

## Ref: https://docs.xebialabs.com/v.9.7/deploy/how-to/configure-the-xl-deploy-sql-repository/#location-of-the-repository
## Ref: https://docs.xebialabs.com/v.9.7/deploy/docker/docker-environment-variables/
UseExistingDB:
  Enabled: false
  # If you want to use an existing database, change the the value to 'true'. Uncomment the following lines and provide the values.
  # XL_DB_URL:
  # XL_DB_USERNAME:
  # XL_DB_PASSWORD:

## Install activemq artemis chart. If you have an existing message queue deployment, set 'install' to 'false'.
activemq-artemis:
  install: true
  fullnameOverride: activemq
  artemisUser: admin
  artemisPassword: admin
  replicas: 1
  persistence:
    enabled: false
    storageClass: "-"

# Ref: https://docs.xebialabs.com/v.9.7/deploy/how-to/configure-task-queueing/#how-it-works
UseExistingMQ:
  Enabled: false
  # If you want to use a existing Message Queue, change the "activemq-artemis.install to false"
  # Set 'UseExistingMQ.Enabled' to 'true'.Uncomment the following lines and provide the values.
  # XLD_TASK_QUEUE_USERNAME:
  # XLD_TASK_QUEUE_PASSWORD:
  # XLD_TASK_QUEUE_URL:
  # XLD_TASK_QUEUE_DRIVER_CLASS_NAME:

## Configure extra options for liveness and readiness probes
HealthProbes: true
HealthProbesLivenessTimeout: 90
HealthProbesReadinessTimeout: 90
HealthProbeFailureThreshold: 12
HealthPeriodScans: 10

nodeSelector: {}

tolerations: []

## Affinity and anti-affinity
## Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
affinity: {}

## XL Deploy data Persistent Volume for 'XL Deploy export'
## If set to "-" or StorageClass: "", pods will not be scheduled
Persistence:
  Enabled: true
  ## Choose storage class provided by your cloud provider, example "ssd" on GKE, AWS and OpenStack
  StorageClass: "-"
  Annotations: {}
  AccessMode: ReadWriteOnce
  Size: 5Gi
