apiVersion: v1
kind: Secret
metadata:
  name: {{ include "xl-deploy.fullname" . }}
  labels:
    app: {{ template "xl-deploy.name" . }}
    chart: {{ template "xl-deploy.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  {{ if .Values.AdminPassword }}
  deploy-password:  {{ .Values.AdminPassword | b64enc | quote }}
  {{ else }}
  deploy-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{ end }}
