{{$XLD_ADMIN_PASS := .Values.AdminPassword | default "admin" }}
{{$XLD_DB_USER := .Values.UseExistingDB.XL_DB_USERNAME | default "xld"}}
{{$XLD_DB_PASS := .Values.UseExistingDB.XL_DB_PASSWORD | default "xld"}}

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "xl-deploy.fullname" . }}-master
  labels:
    chart: {{ template "xl-deploy.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.XldMasterCount }}
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: {{ template "xl-deploy.name" . }}
      component: {{ template "xl-deploy.name" . }}-master
      release: {{ .Release.Name }}
  serviceName: {{ template "xl-deploy.fullname" . }}-master
  template:
    metadata:
      labels:
        app: {{ template "xl-deploy.name" . }}
        component: {{ template "xl-deploy.name" . }}-master
        release: {{ .Release.Name }}
    spec:
      {{- if eq .Values.K8sSetup.Platform "Openshift"}}
      serviceAccountName: {{ template "xl-deploy.name" . }}-sa
      {{- end }}
      initContainers:
        - name: fix-the-volume-permission
          image: xebialabs/tiny-tools
          command:
            - sh
            - -c
            - chown -R 10001 /opt/xebialabs/xl-deploy-server/export
          securityContext:
            privileged: true
          volumeMounts:
            - name: export-dir
              mountPath: /opt/xebialabs/xl-deploy-server/export
        {{- if not .Values.UseExistingDB.Enabled }}
        - name: wait-for-postgresql
          image: xebialabs/tiny-tools
          command:
            - sh
            - -c
            - >
              until nc -z -w 2 $POSTGRES_SVC $POSTGRES_PORT && echo database ok; do
              sleep 2;
              done;
          env:
            - name: POSTGRES_SVC
              value: {{ template "xl-deploy.fullname" . }}-postgresql
            - name: POSTGRES_PORT
              value: "5432"
        {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.ImageRepository }}:{{ .Values.ImageTag }}"
          imagePullPolicy: "{{ .Values.ImagePullPolicy }}"
          ports:
            - name: http
              containerPort: 4516
              protocol: TCP
            - name: jmx-exporter
              containerPort: 9100
            - name: akka
              containerPort: 8180
          volumeMounts:
            - name: export-dir
              mountPath: /opt/xebialabs/xl-deploy-server/work
          {{- if .Values.HealthProbes }}
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: {{ .Values.HealthProbesLivenessTimeout }}
            periodSeconds: {{ .Values.HealthPeriodScans }}
            failureThreshold: {{ .Values.HealthProbeFailureThreshold }}
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: {{ .Values.HealthProbesReadinessTimeout }}
            periodSeconds: {{ .Values.HealthPeriodScans }}
            failureThreshold: {{ .Values.HealthProbeFailureThreshold }}
          {{- end }}
          env:
            - name: ADMIN_PASSWORD
              value: {{$XLD_ADMIN_PASS}}
            - name: XL_CLUSTER_MODE
              value: default
            - name: XL_DB_URL
              {{- if not .Values.UseExistingDB.Enabled }}
              value: jdbc:postgresql://{{ template "xl-deploy.fullname" . }}-postgresql:5432/xld-db
              {{- else }}
              value: {{.Values.UseExistingDB.XL_DB_URL}}
              {{- end }}
            - name: XL_DB_USERNAME
              value: {{$XLD_DB_USER}}
            - name: XL_DB_PASSWORD
              value: "{{$XLD_DB_PASS}}"
            - name: XL_LICENSE
              value: "{{ .Values.xldLicense }}"
            - name: XL_METRICS_ENABLED
              value: "false"
            - name: FORCE_UPGRADE
              value: "true"
            - name: XLD_IN_PROCESS
              value: "false"
            - name: HOSTNAME_SUFFIX
              value: ".{{ template "xl-deploy.fullname" . }}-master.{{.Release.Namespace}}.svc.cluster.local"
            {{- with .Values.MessageQueue }}
            - name: XLD_TASK_QUEUE_DRIVER_CLASS_NAME
              value: {{ .DriverClassName }}
            - name: XLD_TASK_QUEUE_URL
              value: {{ .URL }}
            - name: XLD_TASK_QUEUE_USERNAME
              value: {{ .UserName }}
            - name: XLD_TASK_QUEUE_PASSWORD
              value: {{ .Password }}
            {{- end }}
            - name: REPOSITORY_KEYSTORE
              value: {{ .Values.RepositoryKeystore }}
            - name: REPOSITORY_KEYSTORE_PASSPHRASE
              value: {{ .Values.KeystorePassphrase }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
      volumes:
        - name: export-dir
          persistentVolumeClaim:
            claimName: {{ template "xl-deploy.fullname" . }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
