{{$XLD_DB_USER := .Values.UseExistingDB.XL_DB_USERNAME | default "xld"}}
{{$XLD_DB_PASS := .Values.UseExistingDB.XL_DB_PASSWORD | default "xld"}}

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "xl-deploy.fullname" . }}-worker
  labels:
    chart: {{ template "xl-deploy.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.XldWorkerCount }}
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: {{ template "xl-deploy.name" . }}
      component: {{ template "xl-deploy.name" . }}-worker
      release: {{ .Release.Name }}
  serviceName: {{ template "xl-deploy.fullname" . }}-worker
  template:
    metadata:
      labels:
        app: {{ template "xl-deploy.name" . }}
        component: {{ template "xl-deploy.name" . }}-worker
        release: {{ .Release.Name }}
    spec:
      {{- if eq .Values.K8sSetup.Platform "Openshift"}}
      serviceAccountName: {{ template "xl-deploy.name" . }}-sa
      {{- end }}
      initContainers:
        - name: fix-the-volume-permission
          image: xebialabs/tiny-tools
          command:
            - sh
            - -c
            - chown -R 10001 /opt/xebialabs/xl-deploy-server/work
          securityContext:
            privileged: true
          volumeMounts:
            - name: work-dir
              mountPath: /opt/xebialabs/xl-deploy-server/work
        {{- if not .Values.UseExistingDB.Enabled }}
        - name: wait-for-postgresql
          image: xebialabs/tiny-tools
          command:
            - sh
            - -c
            - >
              until nc -z -w 2 $POSTGRES_SVC $POSTGRES_PORT && echo database ok; do
              sleep 2;
              done;
          env:
            - name: POSTGRES_SVC
              value: {{ template "xl-deploy.fullname" . }}-postgresql
            - name: POSTGRES_PORT
              value: "5432"
        {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.ImageRepository }}:{{ .Values.ImageTag }}"
          imagePullPolicy: "{{ .Values.ImagePullPolicy }}"
          ports:
            - name: jmx-exporter
              containerPort: 9100
            - name: akka
              containerPort: 8180
          volumeMounts:
            - name: work-dir
              mountPath: /opt/xebialabs/xl-deploy-server/work
          {{- if .Values.HealthProbes }}
          readinessProbe:
            tcpSocket:
              port: 8180
            initialDelaySeconds: {{ .Values.HealthProbesReadinessTimeout }}
            periodSeconds: {{ .Values.HealthPeriodScans }}
            failureThreshold: {{ .Values.HealthProbeFailureThreshold }}
          {{- end }}
          env:
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "xl-deploy.fullname" . }}
                  key: deploy-password
            - name: XL_CLUSTER_MODE
              value: default
            - name: XL_DB_URL
              {{- if not .Values.UseExistingDB.Enabled }}
              value: jdbc:postgresql://{{ template "xl-deploy.fullname" . }}-postgresql:5432/xld-db
              {{- else }}
              value: {{.Values.UseExistingDB.XL_DB_URL}}
              {{- end }}
            - name: XL_DB_USERNAME
              value: {{$XLD_DB_USER}}
            - name: XL_DB_PASSWORD
              value: "{{$XLD_DB_PASS}}"
            - name: XL_LICENSE
              value: "{{ .Values.xldLicense }}"
            - name: XL_METRICS_ENABLED
              value: "false"
            - name: FORCE_UPGRADE
              value: "false"
            - name: XLD_IN_PROCESS
              value: "false"
            - name: HOSTNAME_SUFFIX
              value: ".{{ template "xl-deploy.name" . }}"
            {{- if index .Values "activemq-artemis" "install" }}
            - name: XLD_TASK_QUEUE_USERNAME
              value: {{ index .Values "activemq-artemis" "artemisUser" }}
            - name: XLD_TASK_QUEUE_PASSWORD
              value: {{ index .Values "activemq-artemis" "artemisPassword" | quote }}
            - name: XLD_TASK_QUEUE_URL
              value: "tcp://{{ index .Values "activemq-artemis" "fullnameOverride" }}.{{ .Release.Namespace }}.svc.cluster.local:61616"
            - name: XLD_TASK_QUEUE_DRIVER_CLASS_NAME
              value: org.apache.activemq.ActiveMQConnectionFactory
            {{- else }}
            {{- if .Values.UseExistingMQ.Enabled }}
            - name: XLD_TASK_QUEUE_USERNAME
              value: {{ .Values.UseExistingMQ.XLD_TASK_QUEUE_USERNAME }}
            - name: XLD_TASK_QUEUE_PASSWORD
              value: {{ .Values.UseExistingMQ.XLD_TASK_QUEUE_PASSWORD | quote }}
            - name: XLD_TASK_QUEUE_URL
              value: {{ .Values.UseExistingMQ.XLD_TASK_QUEUE_URL | quote }}
            - name: XLD_TASK_QUEUE_DRIVER_CLASS_NAME
              value: {{ .Values.UseExistingMQ.XLD_TASK_QUEUE_DRIVER_CLASS_NAME }}
            {{- end }}
            {{- end }}
            - name: REPOSITORY_KEYSTORE
              value: {{ .Values.RepositoryKeystore }}
            - name: REPOSITORY_KEYSTORE_PASSPHRASE
              value: {{ .Values.KeystorePassphrase }}
          args:
            - "worker"
            - "-master"
            - "{{ template "xl-deploy.fullname" . }}-master.{{.Release.Namespace}}.svc.cluster.local:8180"
            - "-api"
            - "http://{{ template "xl-deploy.fullname" . }}-lb.{{ .Release.Namespace }}.svc.cluster.local:4516/"
          resources:
{{ toYaml .Values.resources | indent 12 }}
      volumes:
        {{- if .Values.Persistence.Enabled }}
        - name: work-dir
          persistentVolumeClaim:
            claimName: {{ template "xl-deploy.fullname" . }}
        {{- else }}
        - name: work-dir
          hostPath:
            path: /opt/xebialabs/xl-deploy-server/work
            type: DirectoryOrCreate
        {{- end }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
